version: '3'

services:
  database:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: dev_api
    environment:
      MIX_ENV: dev
      DATABASE_URL: database
    command: iex -S mix
    ports:
      - "4000:4000"
      - "8080:8080"
    depends_on:
      - database
